version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=localhost
    ports:
      - 5433:5432
  web:
    container_name: myproject
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/Demo/
    depends_on:
      - db