version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=echologyx
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=echologyx
      - POSTGRES_HOST=localhost
    ports:
      - 5433:5432
  web:
    container_name: echologyx
    build:
      context: .
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    # ports:
    #   - 8000:8000
    command: gunicorn echologyx.wsgi:application --bind 0.0.0.0:8000
    expose:
    - 8000
    volumes:
      - ./:/Demo/
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web