# Generated by Django 3.2.7 on 2022-06-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlisttemplate',
            old_name='created_by',
            new_name='activated_by',
        ),
    ]
