# Generated by Django 3.2.7 on 2022-06-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_management', '0002_rename_created_by_postlisttemplate_activated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlisttemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
