# Generated by Django 3.1.4 on 2022-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_management', '0003_alter_postlisttemplate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlisttemplate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
