# Generated by Django 3.2.7 on 2022-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
