# Generated by Django 3.2.7 on 2022-06-09 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogpost', '0002_alter_postcomment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.blogpost'),
        ),
    ]
