# Generated by Django 3.2.7 on 2022-06-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20220609_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-created_at'], name='blogpost_bl_created_d5e742_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_active'], name='blogpost_bl_is_acti_bcfbd5_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['-created_at'], name='blogpost_po_created_b0b744_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['is_active'], name='blogpost_po_is_acti_ee90d3_idx'),
        ),
    ]
